# Site settings
title: CI and CD with GitHub
description: A demo blog
email: foo@example.com
twitter_username: foo
github_username:  bar
baseurl:
url: https://phil0xf7-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
